name: noisy
description: Package designed to provide real-time information about your current geographical coordinates and ambient sound intensity levels.

publish_to: "none"

version: 1.1.0-f+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.0
  noise_meter: ^3.0.1
  syncfusion_flutter_charts: ^19.1.67
  url_launcher: ^6.0.6
  google_fonts: ^2.1.0
  location: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
